afip:
    parameters:
        CUIT: 20298505216
        production: false
        res_folder: 'config/afip/'
        ta_folder:  'var/cache/'
        cert: 'cert'
        key: 'key'
        passphrase: ''
