afip:
    parameters:
        CUIT: 20306094905
        production: false
        res_folder: 'src/Afip_res/'
        ta_folder: 'src/Afip_res/'
        cert: 'cert'
        key: 'key'
        passphrase: ''
